# Generated by Django 3.1.1 on 2020-09-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImageApp', '0002_auto_20200908_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='inputimage.png', max_length=255),
        ),
    ]
