# Generated by Django 3.1.1 on 2020-09-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImageApp', '0003_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='inputimageNEW.png', max_length=255),
        ),
    ]
