# Generated by Django 3.1.1 on 2020-09-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImageApp', '0005_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='result',
            new_name='cell_condition',
        ),
    ]
